---
defaultGroups:
    - wheel
    - audio
    - video
    - storage
    - network
    - input
autoLogin: false
sudoersGroup: wheel
setRootPassword: false
doReusePassword: true
passwordRequirements:
    minLength: 1
    libpwquality:
        - minlen=1
