---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false
requirements:
    requiredStorage: 12
    requiredRam: 1.7
    check:
        - storage
        - ram
        - root
    required:
        - storage
        - ram
        - root
